---
- name: Fireworks Build Server
  hosts: all
  become: true

  vars:
    common_timezone: "America/New_York"

    # in case there are roles that install/update non-global
    # configuration should look at `nonroot_user` var to
    # find out who is the default user in the system
    nonroot_user: "vagrant"
    nonroot_user_home: "/home/vagrant"

    docker_compose_version: "v2.4.1"
    docker_users: [ "vagrant" ]

  roles:
    - geerlingguy.docker
